#!/bin/bash

#for each node, run install process
#for i in `find . -type d -name '[1-9]*'` ;do
for i in ls -1 `find . -maxdepth 0 -type d -name '[1-9]*'`; do

    DEFAULT="N"
    read -e -p "Proceed $i installation ? [N/y/q]:" PROCEED
    PROCEED="${PROCEED:-${DEFAULT}}"
    if [ "${PROCEED}" == "y" ] ; then
        echo ">>>> Node $i: Installing"
        cd $i/
	bash ./install
        echo "#### Node $i: Installation done"
    else
        echo "#### Installation $i aborded !"
    fi

done
