#!/usr/bin/env bash


DEFAULT="q"
read -e -p "
Current hardware role ?    
[1] : Computer (Master, Logics, Database) 
[2] : Robot manager (Physics, Robot) 
[3] : Capture manager 
[4] : Bodies manager  
[5] : Frames manager  
[6] : Store manager  
[q] : quit build program (and terminate current script execution)
": PROCEED
PROCEED="${PROCEED:-${DEFAULT}}"

case "$PROCEED" in
	1)
		BUILD_PATH="10_Computer"
		;;
	2)
		BUILD_PATH="20_Robot"
		;;
	3)
		BUILD_PATH="30_Capture"
		;;
	4)
		BUILD_PATH="40_Bodies"
		;;
	5)
		BUILD_PATH="50_Frames"
		;;
	6)
		BUILD_PATH="60_Store"
		;;

	*)

		exit 1
esac

if [[ "$PROCEED" =~ ^[1-6]+$ ]]; then
	echo ">>>> Starting installation program"
	cd $BUILD_PATH/
	echo $(pwd)
	sudo bash ./install
else
        echo "#### invalid entry, please relaunch program after terminating"
fi

echo "#### installation aborded !"



