#!/usr/bin/env bash

##############################################################################
#Autor: Adrien Beaudrey
#Version: 0.1
#Date: 2019.08.03
#Title: Install 
#Purpose: Deploy a specific "role" of software for ARA (Apiary Robotic Assistant)
#Site: https://apiarobotics.com
#
#
##############################################################################

#Current hardware role ?    
#[1] : Computer (Master, Logics, Database) 
#[2] : Robot manager (Physics, Robot) 
#[3] : Capture manager 
#[4] : Bodies manager  
#[5] : Frames manager  
#[6] : Store manager  
#[q] : quit build program (and terminate current script execution)

# read var from Global config file:
source 00_Global/Global
clear

echo "##########################################"
echo "#Welcome in install process for $APP_NAME"
echo "##########################################"
echo ""
echo ">>>> Starting scan of role to deploy"
echo ""

#scan current directory for ARA software architecture detection and list all role availables in version package && local config settings.

#echo $(ls [1-9]* -d)

#scan current dir then construct array to "store" list of role folders.
i=0 #(technical index = functional index -1)
k=1 #(functional index = technical index + 1)
declare -a ROLES
for role in [1-9]*; do
	#echo "i = $i , role = $role"
	ROLES[$i]=$role
	((i++))
	((k++))
done

ROLE_NB=${#ROLES[*]}

list=''
j=1
m=0

# once array built print to console
echo "#### Scan finished, $ROLE_NB roles availables:"

for role in ${ROLES[*]}; do
	echo "#### [$j] = $role"
#	echo $role 
#	echo ${ROLES[$m]}
	list=$list"[$j] "
	((j++))
	((m++))
done

echo ""

# show request form to select role to deploy (-> start install file hosted in each "role" folder) 
DEFAULT="q"
read -e -p ":::: Choose role to deploy ($list) or [q] to quit": PROCEED
PROCEED="${PROCEED:-${DEFAULT}}"

# execute plan: go to "role" folder and run "build" script
if [[ "$PROCEED" =~ ^[1-6]+$ ]]; then
	#echo "P = $PROCEED"
	n=$(($PROCEED-1))
	#echo "n = $n"
	PATH=${ROLES[$n]}
	echo ""
	echo ">>>> Starting builder program (Role = $PATH)"
	#echo $(pwd)
	#export ROLE=$PATH
	/bin/bash ./build

    #############################################################
    
    # go to "role" folder:
    cd $PATH/
    #echo $(pwd)
    
    # for each folder (node) inside role root folder: 
    for i in [1-9]*; do
    	echo "Node $i"
    	echo ""
    	# test folder is patern validated:
    	#if [[ "$i" =~ [â-zA-Zà-9\ ] ]]; then
    		# yes folder name follows patern
        		DEFAULT="N"
        		read -e -p "Proceed $i installation ? [N/y/q]:" PROCEED
        		PROCEED="${PROCEED:-${DEFAULT}}"
        		if [ "${PROCEED}" == "y" ] ; then
            		echo ">>>> Node $i: Installing"
    			cd $i/
    			echo $(pwd)
    			source ./Local
    			#/bin/bash $GLOBAL_PATH/0g_install.sh

			#############################################################
			
			
			
			#############################################################

            		echo "#### Node $i: Installation done"
        		else
            		echo "#### Installation $i aborded !"
        		fi
    	#fi
    done
    
    #############################################################

else
        echo "#### invalid entry, please relaunch program after terminating"
fi

echo "#### installation aborded !"



